plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-2.0.0-rc.34.cjs
preferInteractive: true
